=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/prodotti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="prodotti">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="prodotto" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

 <xsd:element name="prodotto">
<xsd:complexType>
 <xsd:sequence>
   <xsd:element ref="nome" minOccurs="1" maxOccurs="1"/>
   <xsd:element ref="categoria" minOccurs="1" maxOccurs="1"/>
   <xsd:element ref="descrizione" minOccurs="0" maxOccurs="1"/>
   <xsd:element ref="prezzo" minOccurs="1"/>
   <xsd:element ref="bonus" minOccurs="1"/>
   <xsd:element ref="data_inserimento" minOccurs="0" maxOccurs="1"/>
   <xsd:element ref="immagine" minOccurs="0" maxOccurs="1"/>
 </xsd:sequence>
 <xsd:attribute name="id" type="xsd:integer" use="required"/>
</xsd:complexType>
 </xsd:element>

  <xsd:element name="nome">
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:maxLength value="50"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>

  <xsd:element name="categoria">
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:maxLength value="50"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>

  <xsd:element name="descrizione" type="xsd:string"/>
  <xsd:element name="prezzo" type="xsd:float"/>
  <xsd:element name="bonus" type="xsd:float"/>
  <xsd:element name="data_inserimento" type="xsd:date"/>

  <xsd:element name="immagine">
    <xsd:simpleType>
      <xsd:restriction base="xsd:string">
        <xsd:maxLength value="255"/>
      </xsd:restriction>
    </xsd:simpleType>
  </xsd:element>
</xsd:schema>

=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/prodotti.xml
<?xml version="1.0" encoding="UTF-8"?>

<prodotti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
    xsi:noNamespaceSchemaLocation="prodotti.xsd">
    
 <prodotto id="1">
    <nome>Chitarra Elettrica Fender Stratocaster</nome>
    <categoria>Strumenti a corda</categoria>
    <descrizione>Chitarra elettrica a sei corde, corpo in ontano, manico in acero.</descrizione>
    <prezzo>999.99</prezzo>
    <bonus>100.00</bonus>
    <data_inserimento>2025-05-05</data_inserimento>
    <immagine>../img/fender_stratocaster.jpg</immagine>
</prodotto>

 <prodotto id="2">
    <nome>Album - The Dark Side of the Moon</nome>
    <categoria>dischi</categoria>
    <descrizione>Iconico album dei Pink Floyd, versione rimasterizzata.</descrizione>
    <prezzo>19.99</prezzo>
    <bonus>10.00</bonus>
    <data_inserimento>2025-05-05</data_inserimento>
    <immagine>../img/Dark_side_of_the_moon.jpg</immagine>
 </prodotto>

</prodotti>
