=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/recensioni.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

 <xsd:element name="recensioni">
  <xsd:complexType>
   <xsd:sequence>
    <xsd:element ref="recensione" minOccurs="0" maxOccurs="unbounded"/>
   </xsd:sequence>
  </xsd:complexType>
 </xsd:element>
  
  <xsd:element name="recensione">
   <xsd:complexType>
    <xsd:sequence>
     <xsd:element ref="id_prodotto" minOccurs="1" maxOccurs="1"/>
     <xsd:element ref="id_utente" minOccurs="1" maxOccurs="1"/>
     <xsd:element ref="commento" minOccurs="0"/>
     <xsd:element ref="valutazione" minOccurs="1" maxOccurs="1"/>
     <xsd:element ref="voti_utili" minOccurs="0" maxOccurs="1" />
     <xsd:element ref="voti_inutili" minOccurs="0" maxOccurs="1" />
     <xsd:element ref="data" minOccurs="1" maxOccurs="1"/>
    </xsd:sequence>
    <xsd:attribute name="id" type="xsd:integer" use="required"/>
   </xsd:complexType>
  </xsd:element>

  <xsd:element name="id_prodotto" type="xsd:integer"/>
  <xsd:element name="id_utente" type="xsd:integer"/>
  <xsd:element name="commento" type="xsd:string"/>
  
  <xsd:element name="valutazione">
    <xsd:simpleType>
     <xsd:restriction base="xsd:integer">
      <xsd:minInclusive value="1"/>
      <xsd:maxInclusive value="5"/>
     </xsd:restriction>
   </xsd:simpleType>
  </xsd:element>

  <xsd:element name="voti_utili" type="xsd:integer" default="0"/>
  <xsd:element name="voti_inutili" type="xsd:integer" default="0"/>
  <xsd:element name="data" type="xsd:date"/>

</xsd:schema>

=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/recensioni.xml
<?xml version="1.0" encoding="UTF-8"?>
<recensioni xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
            xsi:noNamespaceSchemaLocation="recensioni.xsd">
  <recensione id="1">
    <id_prodotto>1</id_prodotto>
    <id_utente>5</id_utente>
    <commento>Ottimo prodotto, qualita' eccellente.</commento>
    <valutazione>5</valutazione>
    <voti_utili>3</voti_utili>
    <voti_inutili>0</voti_inutili>
    <data>2025-05-10</data>
  </recensione>

  <recensione id="2">
    <id_prodotto>2</id_prodotto>
    <id_utente>2</id_utente>
    <commento>Arrivato in ritardo ma funziona bene.</commento>
    <valutazione>4</valutazione>
    <voti_utili>2</voti_utili>
    <voti_inutili>1</voti_inutili>
    <data>2025-05-11</data>
  </recensione>
</recensioni>
