=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/storico_crediti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">

    <!-- ELEMENTO RADICE -->
    <xsd:element name="storici_crediti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="record" minOccurs="0" maxOccurs="unbounded"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- ELEMENTO RECORD -->
    <xsd:element name="record">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="id_utente" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="data" minOccurs="1" maxOccurs="1"/>
                <xsd:element ref="crediti" minOccurs="1" maxOccurs="1"/>
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <!-- ELEMENTI BASE -->
    <xsd:element name="id_utente" type="xsd:integer"/>
    <xsd:element name="data" type="xsd:date"/>
    <xsd:element name="crediti">
        <xsd:simpleType>
            <xsd:restriction base="xsd:decimal">
                <xsd:minInclusive value="0"/>
                <xsd:maxInclusive value="100000"/>
            </xsd:restriction>
        </xsd:simpleType>
    </xsd:element>

</xsd:schema>

=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/storico_crediti.xml
<?xml version="1.0" encoding="UTF-8"?>
<storici_crediti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="storico_crediti.xsd">
  <record>
    <id_utente>4</id_utente>
    <data>2025-10-23</data>
    <crediti>193</crediti>
  </record>
  <record>
    <id_utente>4</id_utente>
    <data>2025-10-23</data>
    <crediti>213</crediti>
  </record>
  <record>
    <id_utente>4</id_utente>
    <data>2025-10-23</data>
    <crediti>263</crediti>
  </record>
  <record>
    <id_utente>4</id_utente>
    <data>2025-10-23</data>
    <crediti>363</crediti>
  </record>
  <record>
    <id_utente>4</id_utente>
    <data>2025-10-23</data>
    <crediti>393</crediti>
  </record>
  <record>
    <id_utente>4</id_utente>
    <data>2025-10-23</data>
    <crediti>398</crediti>
  </record>
  <record>
    <id_utente>4</id_utente>
    <data>2025-10-23</data>
    <crediti>598</crediti>
  </record>
  <record>
    <id_utente>7</id_utente>
    <data>2025-10-23</data>
    <crediti>200</crediti>
  </record>
  <record>
    <id_utente>8</id_utente>
    <data>2025-10-23</data>
    <crediti>50</crediti>
  </record>
  <record>
    <id_utente>8</id_utente>
    <data>2025-10-23</data>
    <crediti>160</crediti>
  </record>
</storici_crediti>
