=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/storico_acquisti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <xsd:element name="storici">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="storico" minOccurs="0" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="storico">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="id_utente"/>
        <xsd:element ref="data"/>
        <xsd:element ref="prodotti"/>
        <xsd:element ref="prezzo_totale_ordine"/>
      </xsd:sequence>
      <xsd:attribute name="id" type="xsd:integer" use="required"/>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="prodotti">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="prodotto" minOccurs="1" maxOccurs="unbounded"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="prodotto">
    <xsd:complexType>
      <xsd:sequence>
        <xsd:element ref="id_prodotto"/>
        <xsd:element ref="quantita"/>
        <xsd:element ref="prezzo_unitario"/>
        <xsd:element ref="prezzo_totale"/>
      </xsd:sequence>
    </xsd:complexType>
  </xsd:element>

  <xsd:element name="id_utente" type="xsd:integer"/>
  <xsd:element name="data" type="xsd:date"/>
  <xsd:element name="id_prodotto" type="xsd:integer"/>
  <xsd:element name="quantita" type="xsd:integer"/>
  <xsd:element name="prezzo_unitario" type="xsd:float"/>
  <xsd:element name="prezzo_totale" type="xsd:float"/>
  <xsd:element name="prezzo_totale_ordine" type="xsd:float"/>
</xsd:schema>

=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/storico_acquisti.xml
<?xml version="1.0" encoding="UTF-8"?>
<storici xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="Storico_Acquisti.xsd">
  <storico id="1">
    <id_utente>5</id_utente>
    <data>2025-10-15</data>
    <prodotti>
      <prodotto>
        <id_prodotto>1</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>999.99</prezzo_unitario>
        <prezzo_totale>999.99</prezzo_totale>
      </prodotto>
      <prodotto>
        <id_prodotto>3</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>149.99</prezzo_unitario>
        <prezzo_totale>149.99</prezzo_totale>
      </prodotto>
      <prodotto>
        <id_prodotto>5</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>99.99</prezzo_unitario>
        <prezzo_totale>99.99</prezzo_totale>
      </prodotto>
      <prodotto>
        <id_prodotto>6</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>499.99</prezzo_unitario>
        <prezzo_totale>499.99</prezzo_totale>
      </prodotto>
    </prodotti>
    <prezzo_totale_ordine>1749.96</prezzo_totale_ordine>
  </storico>
  <storico id="2">
    <id_utente>4</id_utente>
    <data>2025-10-15</data>
    <prodotti>
      <prodotto>
        <id_prodotto>10</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>8.49</prezzo_unitario>
        <prezzo_totale>8.49</prezzo_totale>
      </prodotto>
      <prodotto>
        <id_prodotto>9</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>42.49</prezzo_unitario>
        <prezzo_totale>42.49</prezzo_totale>
      </prodotto>
    </prodotti>
    <prezzo_totale_ordine>50.98</prezzo_totale_ordine>
  </storico>
  <storico id="3">
    <id_utente>4</id_utente>
    <data>2025-10-17</data>
    <prodotti>
      <prodotto>
        <id_prodotto>7</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>11.04</prezzo_unitario>
        <prezzo_totale>11.04</prezzo_totale>
      </prodotto>
      <prodotto>
        <id_prodotto>8</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>139.99</prezzo_unitario>
        <prezzo_totale>139.99</prezzo_totale>
      </prodotto>
    </prodotti>
    <prezzo_totale_ordine>151.03</prezzo_totale_ordine>
  </storico>
  <storico id="4">
    <id_utente>4</id_utente>
    <data>2025-10-21</data>
    <prodotti>
      <prodotto>
        <id_prodotto>1</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>899.99</prezzo_unitario>
        <prezzo_totale>899.99</prezzo_totale>
      </prodotto>
      <prodotto>
        <id_prodotto>2</id_prodotto>
        <quantita>2</quantita>
        <prezzo_unitario>18.39</prezzo_unitario>
        <prezzo_totale>36.78</prezzo_totale>
      </prodotto>
    </prodotti>
    <prezzo_totale_ordine>936.77</prezzo_totale_ordine>
  </storico>
  <storico id="5">
    <id_utente>4</id_utente>
    <data>2025-10-21</data>
    <prodotti>
      <prodotto>
        <id_prodotto>8</id_prodotto>
        <quantita>2</quantita>
        <prezzo_unitario>178.59</prezzo_unitario>
        <prezzo_totale>357.18</prezzo_totale>
      </prodotto>
      <prodotto>
        <id_prodotto>7</id_prodotto>
        <quantita>2</quantita>
        <prezzo_unitario>11.60</prezzo_unitario>
        <prezzo_totale>23.20</prezzo_totale>
      </prodotto>
    </prodotti>
    <prezzo_totale_ordine>380.38</prezzo_totale_ordine>
  </storico>
  <storico id="6">
    <id_utente>4</id_utente>
    <data>2025-10-21</data>
    <prodotti>
      <prodotto>
        <id_prodotto>9</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>44.64</prezzo_unitario>
        <prezzo_totale>44.64</prezzo_totale>
      </prodotto>
      <prodotto>
        <id_prodotto>10</id_prodotto>
        <quantita>1</quantita>
        <prezzo_unitario>8.92</prezzo_unitario>
        <prezzo_totale>8.92</prezzo_totale>
      </prodotto>
    </prodotti>
    <prezzo_totale_ordine>53.56</prezzo_totale_ordine>
  </storico>
</storici>
