=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/utenti.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <xsd:element name="utenti">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="utente" minOccurs="0" maxOccurs="unbounded" />
            </xsd:sequence>
        </xsd:complexType>
    </xsd:element>

    <xsd:element name="utente">
        <xsd:complexType>
            <xsd:sequence>
                <xsd:element ref="nome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="cognome" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="telefono" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="indirizzo" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="reputazione" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="stato" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="portafoglio" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="crediti" minOccurs="1" maxOccurs="1" />
                <xsd:element ref="data_iscrizione" minOccurs="1" maxOccurs="1" />
            </xsd:sequence>
            <xsd:attribute name="id" type="xsd:integer" use="required" />
        </xsd:complexType>
    </xsd:element>
    <xsd:element name="nome" type="xsd:string" />
    <xsd:element name="cognome" type="xsd:string" />
    <xsd:element name="telefono" type="xsd:string" />
    <xsd:element name="indirizzo" type="xsd:string" />
    <xsd:element name="reputazione" type="xsd:float" />
    <xsd:element name="stato" type="xsd:boolean" />
    <xsd:element name="portafoglio" type="xsd:float" />
    <xsd:element name="crediti" type="xsd:float" />
    <xsd:element name="data_iscrizione" type="xsd:date" />
</xsd:schema>

=== BrigAle/JAM-MusicStore-Tesina/risorse/XML/utenti.xml
<?xml version="1.0" encoding="UTF-8"?>
<utenti xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="utenti.xsd">
  <utente id="1">
    <nome>Admin</nome>
    <cognome>Admin</cognome>
    <telefono>0000000000</telefono>
    <indirizzo>Via Roma, 1</indirizzo>
    <reputazione>0</reputazione>
    <portafoglio>0</portafoglio>
    <crediti>0</crediti>
    <data_iscrizione>2025-01-02</data_iscrizione>
  </utente>
  <utente id="2">
    <nome>Alessandro</nome>
    <cognome>Brighenti</cognome>
    <telefono>1234567890</telefono>
    <indirizzo>Via Milano, 10</indirizzo>
    <reputazione>0</reputazione>
    <portafoglio>0</portafoglio>
    <crediti>0</crediti>
    <data_iscrizione>2025-01-02</data_iscrizione>
  </utente>
  <utente id="3">
    <nome>Giovanni</nome>
    <cognome>Tagliaferri</cognome>
    <telefono>0987654321</telefono>
    <indirizzo>Via Napoli, 5</indirizzo>
    <reputazione>0</reputazione>
    <portafoglio>0</portafoglio>
    <crediti>0</crediti>
    <data_iscrizione>2025-01-02</data_iscrizione>
  </utente>
  <utente id="4">
    <nome>Mattia</nome>
    <cognome>Aquilina</cognome>
    <telefono>1122334455</telefono>
    <indirizzo>Via Roma, 2</indirizzo>
    <reputazione>21.5</reputazione>
    <portafoglio>2624.89</portafoglio>
    <crediti>598</crediti>
    <data_iscrizione>2025-01-02</data_iscrizione>
  </utente>
  <utente id="5">
    <nome>Denis</nome>
    <cognome>Boitor</cognome>
    <telefono>343434343</telefono>
    <indirizzo>Via Firenze 25, LT</indirizzo>
    <reputazione>0</reputazione>
    <portafoglio>0</portafoglio>
    <crediti>0</crediti>
    <data_iscrizione>2025-01-02</data_iscrizione>
  </utente>
  <utente id="6">
    <nome>Andrea</nome>
    <cognome>Mattarelli</cognome>
    <telefono>324234232</telefono>
    <indirizzo>Via monte terminillo 48, LT 04100</indirizzo>
    <reputazione>0</reputazione>
    <portafoglio>5000</portafoglio>
    <crediti>0</crediti>
    <data_iscrizione>2025-10-23</data_iscrizione>
  </utente>
  <utente id="7">
    <nome>Vincenzo</nome>
    <cognome>Ferrara</cognome>
    <telefono>324232425</telefono>
    <indirizzo>Via cavata 1, LT 04100</indirizzo>
    <reputazione>0</reputazione>
    <portafoglio>4000</portafoglio>
    <crediti>200</crediti>
    <data_iscrizione>2025-10-23</data_iscrizione>
  </utente>
  <utente id="8">
    <nome>Daniele</nome>
    <cognome>Ardovini</cognome>
    <telefono>393465728</telefono>
    <indirizzo>Via Sandro Pertini 11, Ceccano FR</indirizzo>
    <reputazione>13</reputazione>
    <portafoglio>3000</portafoglio>
    <crediti>160</crediti>
    <data_iscrizione>2025-10-23</data_iscrizione>
  </utente>
  <utente id="9">
    <nome>Daniele</nome>
    <cognome>Brighenti</cognome>
    <telefono>3234455</telefono>
    <indirizzo>Via gaeta 49 LT 04100</indirizzo>
    <reputazione>0</reputazione>
    <portafoglio>0</portafoglio>
    <crediti>0</crediti>
    <data_iscrizione>2025-10-23</data_iscrizione>
  </utente>
</utenti>
